/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luisb' at '10/11/16 12:04' with Gradle 3.1
 *
 * @author luisb, @date 10/11/16 12:04
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
